# Configuration for upptime
---
owner: india-ultimate
repo: status

sites:
  - name: Hub (prod)
    url: https://hub.indiaultimate.org
  - name: Hub (staging)
    url: https://upai-hub-staging.fly.dev/

status-website:
  cname: status.indiaultimate.org
  logoUrl: "https://raw.githubusercontent.com/india-ultimate/hub/blob/main/frontend/assets/logo-vertical.png"
  name: India Ultimate Web Status page
  introTitle: Status page for sites related to India Ultimate
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  # try to run cron every 10 minutes; GitHub actions aren't easily controllable
  # and the exact schedule depends on the GitHub Actions scheduler.
  uptime: "4,14,24,34,44,54 * * * *"
